### ISSUE TITLE
Misplaced arrows in the MODS tab

### ISSUE THREAD

**Issue by Agent517** [rphsoftware/OneLoader#1]
Self explanatory.
Mod list is as follows, should it matter:
- 400% speed fear music
- UI Fixes
- State Icons
- Chicken Respawn
- Controller UI Overhaul
- Save Drag and Drop
- Enable Debugger
- Fast COFFEE
- Hero Buff
- Mewocharm
- Omori Fight Plus
- OneLoader
- Photo Album Extended
- Portable Picnic Basket
- Playtest maker
- Run in Background
- Improved Save & Load
- Save Saver
- Shiba Hoodie Kel
- Smile More
- Tag VA

![image](https://user-images.githubusercontent.com/87152256/124992171-a4910c80-e010-11eb-9d61-9247a3c7b613.png)

![image](https://user-images.githubusercontent.com/87152256/124992034-73184100-e010-11eb-9004-958d16d1a3e6.png)

![image](https://user-images.githubusercontent.com/87152256/124992054-7a3f4f00-e010-11eb-8a3c-5768e99a1304.png)

**Comment by rphsoftware** [comment]
Mod compat bug, narrowed down to Controller UI Overhaul, planned fix for Preview 3
