### ISSUE TITLE
Package.json modification

### ISSUE THREAD

**Issue by FoGsesipod** [rphsoftware/OneLoader#18]
pretty straight forward, allow us to delta/addon to package.json
reasoning/use case
`"chromium-args" : "--force-device-scale-factor=1"` 
so that running the game on higher non factors of 100% scaling doesnt make pixels look like crap (125%, 150%, 175%, 225%, 250% etc.)

**Comment by rphsoftware** [comment]
Implementation proposal:
In mod.json, there will be a new optional field: "packagejson_delta". The content of that will be a delta object, as follows:
```json
{
 "id":"mod",
 "packagejson_delta": [
  /* delta here */
 ]
}
```

Enabling this would also require the `package_json_editing` flag, just to make it an explicit opt-in. Having more than one active mod with this enabled would result in a crash.

@FoGsesipod does this look good?

**Comment by FoGsesipod** [comment]
how would inserting the requested data look then? since package.json already has a `"chromium-args"` field

**Comment by rphsoftware** [comment]
Seeing as JSON delta does not support string editing, I imagine it would have to be the entire value of chromium-args, with the new string appended.

**Comment by FoGsesipod** [comment]
alright yea that should be good then. use case for this is already very slim, so not much chance imo that multiple args would be needed, and if that is the case probably just best the user manually modifies it
