### ISSUE TITLE
Decrypting mods freezes in Preview 3

### ISSUE THREAD

**Issue by Agent517** [rphsoftware/OneLoader#3]
Simple enough.
When decrypting the game with mods, it stops when planning \js\plugins.
![image](https://user-images.githubusercontent.com/87152256/125180541-33488980-e1c9-11eb-83d4-c5bd49014055.png)
When decrypting only mods, it stops on the oneloader-assistant plugin.
![image](https://user-images.githubusercontent.com/87152256/125180562-5c691a00-e1c9-11eb-9aa8-921c0c0d1f3e.png)

It works when decrypting the base game only, and all 3 work in Preview 2.1.

**Comment by rphsoftware** [comment]
Initial triage result:
Potential cause can be the fact that when randomizing plugin names ogName doesn't get set to the randomized string
I'll attempt to fix this and see if it works as a resolution

![image](https://user-images.githubusercontent.com/11350302/125189916-d5548a00-e23a-11eb-9953-795972bbc20d.png)
