### ISSUE TITLE
Cannot close OMORI window when finished decrypting project

### ISSUE THREAD

**Issue by ghost** [rphsoftware/OneLoader#5]
If you drag the OMORI window down so that the pop-up window cannot be interacted with when finished decrypting, you will be unable to close the OMORI window. If you are able to fix that on your end that would be stellar, thanks Rph!

**Comment by FunctionDJ** [comment]
@rphsoftware easiest solution might be to not use alert.

**Comment by rphsoftware** [comment]
You can still focus it from your taskbar and hit enter, please try and confirm/deny

**Comment by ghost** [comment]
Can confirm that works
