### ISSUE TITLE
hi ihave an issue with when i press continue in omori

### ISSUE THREAD

**Issue by kelinthereal** [rphsoftware/OneLoader#7]
[latest.log](https://github.com/rphsoftware/OneLoader/files/7818510/latest.log)
[saveloadplus.zip](https://github.com/rphsoftware/OneLoader/files/7818512/saveloadplus.zip)
[savesaver.zip](https://github.com/rphsoftware/OneLoader/files/7818513/savesaver.zip)
[shibahoodiekel.zip](https://github.com/rphsoftware/OneLoader/files/7818514/shibahoodiekel.zip)
[smilemore.zip](https://github.com/rphsoftware/OneLoader/files/7818515/smilemore.zip)
[somethings_off_about_aubrey.zip](https://github.com/rphsoftware/OneLoader/files/7818516/somethings_off_about_aubrey.zip)
[tagva.zip](https://github.com/rphsoftware/OneLoader/files/7818517/tagva.zip)
[uifixes.zip](https://github.com/rphsoftware/OneLoader/files/7818518/uifixes.zip)
[unusedhospitalcutscene.zip](https://github.com/rphsoftware/OneLoader/files/7818519/unusedhospitalcutscene.zip)
[accessible_enemies.zip](https://github.com/rphsoftware/OneLoader/files/7818520/accessible_enemies.zip)
[canonnames.zip](https://github.com/rphsoftware/OneLoader/files/7818521/canonnames.zip)
[canvasbgon.zip](https://github.com/rphsoftware/OneLoader/files/7818522/canvasbgon.zip)
[controlleruioverhaul.zip](https://github.com/rphsoftware/OneLoader/files/7818523/controlleruioverhaul.zip)
[fastcoffee.zip](https://github.com/rphsoftware/OneLoader/files/7818524/fastcoffee.zip)
[herobuff.zip](https://github.com/rphsoftware/OneLoader/files/7818525/herobuff.zip)
[identityfound.zip](https://github.com/rphsoftware/OneLoader/files/7818526/identityfound.zip)
[keltickleanimation.zip](https://github.com/rphsoftware/OneLoader/files/7818527/keltickleanimation.zip)
[Mari_My_Beloved.zip](https://github.com/rphsoftware/OneLoader/files/7818528/Mari_My_Beloved.zip)
[mewocharm.zip](https://github.com/rphsoftware/OneLoader/files/7818529/mewocharm.zip)
[mirrorplotholefix.zip](https://github.com/rphsoftware/OneLoader/files/7818530/mirrorplotholefix.zip)
[movieondemand.zip](https://github.com/rphsoftware/OneLoader/files/7818531/movieondemand.zip)
[nitpickchainsaw.zip](https://github.com/rphsoftware/OneLoader/files/7818532/nitpickchainsaw.zip)
[no humpry.zip](https://github.com/rphsoftware/OneLoader/files/7818533/no.humpry.zip)
[omocep_splash.zip](https://github.com/rphsoftware/OneLoader/files/7818534/omocep_splash.zip)
[omoriwithcolor.zip](https://github.com/rphsoftware/OneLoader/files/7818535/omoriwithcolor.zip)
[PersuadeSkill.zip](https://github.com/rphsoftware/OneLoader/files/7818536/PersuadeSkill.zip)
[photoalbumextended.zip](https://github.com/rphsoftware/OneLoader/files/7818537/photoalbumextended.zip)
[properwhitesurfstyle.zip](https://github.com/rphsoftware/OneLoader/files/7818538/properwhitesurfstyle.zip)
[revertkeeper.zip](https://github.com/rphsoftware/OneLoader/files/7818539/revertkeeper.zip)
[runinbackground.zip](https://github.com/rphsoftware/OneLoader/files/7818540/runinbackground.zip)

hi, here are all my mods and my log, my omori hasnt been working and has been saying this (attachment below) when i pressed "continue" on the main menu, could you tell me whats wrong, it started when i was playing omori and i was about to do the sweetheart boss fight until i accidentally turned off my computer and i saw this message when i pressed the continue button please help

im not sure if it has to do with my original game or my mods

![error](https://user-images.githubusercontent.com/97202375/148308678-c35257a0-76c4-4628-b54a-8421127ec37c.png)

**Comment by rphsoftware** [comment]
This is most likely an issue with the save file, send your saves so I can look., If you shut down your computer during saving, it's possible the file is corrupted.

**Comment by kelinthereal** [comment]
how do i send my saves? it wont let me attach RPGSAVE files

**Comment by FunctionDJ** [comment]
@kelinthereal i think you need to put them in a ZIP file

**Comment by kelinthereal** [comment]
ah alralr, heres the ZIP file
[saves.zip](https://github.com/rphsoftware/OneLoader/files/7830390/saves.zip)

**Comment by kelinthereal** [comment]
hi guys i fixed it its alr now
