### ISSUE TITLE
Hi , after starting game i see error

### ISSUE THREAD

**Issue by LiMoNtEpro** [rphsoftware/OneLoader#8]
A catastropic failure occured while loading the modloader. (https://user-images.githubusercontent.com/66868587/148458478-f6ab0723-4fef-446a-9e24-b16917699117.png)

**Comment by FunctionDJ** [comment]
Have you tried --no-mods?

**Comment by LiMoNtEpro** [comment]
> Have you tried --no-mods?

yes i tried, it doesn't work

**Comment by vladd12** [comment]
> Have you tried --no-mods?

![image](https://user-images.githubusercontent.com/15172665/156835046-3a230646-ce44-4f1c-83e8-f7938ced86cd.png)

In my case OneLoader stops at the preparing stage with `--no-mods`

**Comment by rphsoftware** [comment]
Is the issue still occuring?

**Comment by MysticLunala** [comment]
Did you correctly install the modloader?

**Comment by MandoTheMisfit** [comment]
I'm also having this issue, nothing works

**Comment by rphsoftware** [comment]
Can't reproduce the issue, not enough information was provided
